name: DATAE Pipeline

on:
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pipeline
        run: |
          python main.py

      - name: Upload final Excel artifact
        uses: actions/upload-artifact@v4
        with:
          name: DATAE_APOYOS_2025_INFORME
          path: output/DATAE_APOYOS_2025_INFORME.xlsx

      - name: Upload debug artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DATAE_DEBUG_OUTPUTS
          path: output/_debug/
